[phases.setup]
nixPkgs = ["maven", "jdk17"]

[phases.install]
cmds = ["cd backend && mvn dependency:go-offline -B"]

[phases.build]
cmds = ["cd backend && mvn clean package -DskipTests"]

[start]
cmd = "cd backend && java -jar target/backend-0.0.1-SNAPSHOT.jar"

